# empezando a programar
primera clase


In [1]:
from pylab import *
%matplotlib inline


integer, float y double

In [6]:
3./2

1.5

In [16]:
a = 1.; b=3
c = a/b
print c

0.333333333333


In [10]:
a*b

2.0

In [11]:
a+b

3.0

In [13]:
a**b

1.0

In [14]:
sqrt(4)

2.0

# vectores

In [23]:
vector1 = [1.,2.,3.,4.]
c = vector1[2]/2

print "el resultado es", c

el resultado es 1.5


In [24]:
print vector1

[1.0, 2.0, 3.0, 4.0]


una lista vector puede tener distintos tipos de elementos

In [25]:
array ([1,2,3,4])

array([1, 2, 3, 4])

# un array tiene que tener los mismos elementos

In [26]:
a =["hola", 2,3.]

In [27]:
a[0]

'hola'

In [28]:
array(["hola",1])

array(['hola', '1'], 
      dtype='|S4')

In [29]:
array[0]

TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'

In [30]:
zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [31]:
zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [43]:
vector2 = ones(8)

In [44]:
vector2[5-1:7] = 7.
print vector2

[ 1.  1.  1.  1.  7.  7.  7.  1.]


In [49]:
vector2[5:8] =[1,2,3]
print vector2

[ 1.  1.  1.  1.  7.  1.  2.  3.]


In [58]:
matriz1 = [[1,2,3],[4,5,6],[7,8,9]]
print matriz1[1][2]


6


In [61]:
matriz2 = zeros((2,3))
print matriz2

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
