In [1]:
x = 3

3

In [2]:
x

3

In [3]:
x = 0.0
data = [x]

for i in 1:1000
    x += randn()
    push!(data, x)
end
    

In [4]:
data

1001-element Array{Float64,1}:
  0.0     
 -0.167419
  0.517047
  1.40641 
  2.27092 
  3.38351 
  4.29829 
  4.78729 
  4.33446 
  6.39404 
  6.63245 
  8.16536 
  8.75152 
  ⋮       
 40.5966  
 41.4589  
 41.8813  
 41.7106  
 43.5313  
 45.7164  
 46.4756  
 45.759   
 43.6603  
 41.5492  
 41.6997  
 40.5456  

In [8]:
using Plots
gr()

Plots.GRBackend()

In [9]:
plot(data)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 200 
 
 
 400 
 
 
 600 
 
 
 800 
 
 
 1000 
 
 
 0 
 
 
 20 
 
 
 40 
 
<polyline clip-path="url(#clip02)" style="stroke:#0099ff; stroke-width:0.8; stroke-opacity:1; fill:none" points="
 21.7148,312.535 22.2891,313.582 22.8635,309.304 23.4378,303.745 24.0122,298.342 24.5865,291.389 25.1609,285.671 25.7352,282.615 26.3096,285.445 26.8839,272.573 
 27.4583,271.083 28.0326,261.502 28.607,257.839 29.1813,249.896 29.7557,238.152 30.33,238.755 30.9044,238.142 31.4787,248.056 32.0531,253.964 32.6274,253.013 
 33.2017,244.333 33.7761,238.725 34.3504,239.154 34.9248,234.206 35.4991,233.108 36.0735,227.689 36.6478,227.125 37.2222,223.798 37.7965,229.248 38.3709,232.072 
 38.9452,234.522 39.5196,234.757 40.0939,236.479 40.6683,232.611 41.2426,240.861 41.817,230.999 42.3913,234.247 42.9657,234.146 43.54,235.628 44.1144,226.396 
 44.6887,234.837 45.2631,231.804 45.8374,233.167 46.4118,228.134 46.9861,222.958 47.5605,221.795 48.1348,217.543 48.7092,214.111 49.2835,201.779 49.8578,208.899 
 50.4322,214.634 51.0065,218.256 51.5809,215.273 52.1552,210.833 52.7296,204.293 53.3039,203.432 53.8783,206.636 54.4526,207.831 55.027,216.425 55.6013,214.971 
 56.1757,218.646 56.75,219.697 57.3244,226.46 57.8987,215.842 58.4731,220.725 59.0474,223.279 59.6218,226.979 60.1961,229.042 60.7705,234.621 61.3448,233.611 
 61.9192,237.424 62.4935,235.332 63.0679,231.135 63.6422,227.845 64.2166,231.248 64.7909,233.252 65.3652,239.172 65.9396,249.174 66.5139,244.51 67.0883,254.04 
 67.6626,256.346 68.237,262.347 68.8113,269.656 69.3857,271.862 69.96,267.907 70.5344,259.623 71.1087,258.093 71.6831,272.395 72.2574,279.707 72.8318,280.959 
 73.4061,283.121 73.9805,291.231 74.5548,299.922 75.1292,294.201 75.7035,296.23 76.2779,294.217 76.8522,286.386 77.4266,281.347 78.0009,273.245 78.5753,278.839 
 79.1496,280.397 79.724,278.117 80.2983,281.5 80.8727,273.167 81.447,272.313 82.0213,275.36 82.5957,266.714 83.17,262.168 83.7444,262.554 84.3187,263.233 
 84.8931,247.164 85.4674,249.139 86.0418,250.878 86.6161,249.159 87.1905,246.349 87.7648,232.887 88.3392,227.319 88.9135,228.372 89.4879,233.162 90.0622,235.979 
 90.6366,242.285 91.2109,243.447 91.7853,251.14 92.3596,263.883 92.934,263.518 93.5083,269.922 94.0827,271.306 94.657,280.762 95.2314,289.083 95.8057,295.119 
 96.3801,299.438 96.9544,310.91 97.5287,311.653 98.1031,297.691 98.6774,297.352 99.2518,302.76 99.8261,303.104 100.4,308.276 100.975,312.218 101.549,297.812 
 102.124,300.433 102.698,306.285 103.272,307.076 103.847,315.656 104.421,319.426 104.995,335.004 105.57,345.848 106.144,355.835 106.718,371.378 107.293,377.892 
 107.867,376.805 108.441,376.92 109.016,384.952 109.59,380.413 110.164,373.86 110.739,354.914 111.313,345.875 111.887,346.536 112.462,355.301 113.036,358.262 
 113.61,364.476 114.185,369.327 114.759,373.433 115.334,371.049 115.908,366.405 116.482,372.751 117.057,375.845 117.631,376.577 118.205,369.744 118.78,369.268 
 119.354,370.825 119.928,374.679 120.503,377.694 121.077,384.728 121.651,382.812 122.226,363.497 122.8,359.534 123.374,358.116 123.949,358.212 124.523,370.012 
 125.097,366.01 125.672,363.632 126.246,362.037 126.821,362.295 127.395,361.557 127.969,373.978 128.544,367.444 129.118,359.165 129.692,356.208 130.267,352.043 
 130.841,349.669 131.415,349.385 131.99,340.709 132.564,334.025 133.138,334.174 133.713,335.192 134.287,338.766 134.861,336.445 135.436,332.339 136.01,337.414 
 136.584,348.003 137.159,344.597 137.733,350.151 138.307,349.876 138.882,362.193 139.456,368.593 140.031,352.444 140.605,346.228 141.179,347.622 141.754,333.225 
 142.328,323.325 142.902,327.153 143.477,324.241 144.051,322.893 144.625,323.14 145.2,312.497 145.774,312.38 146.348,300.672 146.923,302.346 147.497,300.746 
 148.071,299.996 148.646,300.649 149.22,306.325 149.794,307.367 150.369,305.529 150.943,310.836 151.517,317.512 152.092,322.333 152.666,329.151 153.241,332.392 
 153.815,327.168 1

In [1]:
function trayectoria(N=1000)
    x = y = 0.0
    data = zeros(N, 2)
    
    for i in 1:N
        x += randn()
        y += randn()

        data[i, :] = [x, y]
    end
    
    return data
end
    

trayectoria (generic function with 2 methods)

In [3]:
trayecs = [trayectoria(100) for i in 1:10000];

In [27]:
p = plot()

for i in 1:length(trayecs)
    plot!(trayecs[i][:,1], trayecs[i][:,2])
end

LoadError: UndefVarError: trayecs not defined

In [12]:
using Plots; gr()

Plots.GRBackend()

In [8]:
[i^2 for i in 1:10]

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [19]:
xs = [trayecs[i][end,1] for i in 1:length(trayecs)]
ys = [trayecs[i][end,2] for i in 1:length(trayecs)]

10000-element Array{Float64,1}:
 -23.9469  
  11.1828  
  -0.556261
  -1.88684 
 -11.1615  
   4.75456 
  -2.12035 
 -14.4675  
  -9.3884  
 -10.1607  
  16.0884  
  11.0423  
  -5.62398 
   ⋮       
   8.23429 
 -12.0991  
  -3.78938 
   4.6164  
   0.544193
  -2.90262 
   4.46773 
  -1.17903 
  10.1928  
 -10.8325  
  -0.776113
   4.69735 

In [20]:
ys

10000-element Array{Float64,1}:
 -23.9469  
  11.1828  
  -0.556261
  -1.88684 
 -11.1615  
   4.75456 
  -2.12035 
 -14.4675  
  -9.3884  
 -10.1607  
  16.0884  
  11.0423  
  -5.62398 
   ⋮       
   8.23429 
 -12.0991  
  -3.78938 
   4.6164  
   0.544193
  -2.90262 
   4.46773 
  -1.17903 
  10.1928  
 -10.8325  
  -0.776113
   4.69735 

In [26]:
histogram2d(xs, ys, nbins=30)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -20 
 
 
 0 
 
 
 20 
 
 
 -20 
 
 
 0 
 
 
 20 
 
 
<image width="505" height="381" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAfkAAAF9CAYAAAAHlxEqAAAQJUlEQVR4nO3dy49k51nH8fdUVV/c
PTePZzx2xh7ATkAg2USWFZCIhATewd/KBpZBKEIJsgQJUYgSy3GMje2ZiefimZ6uvtY5LEiIAkQs
fq/pw6PPZ38evVXVVd8+m/MMDWZuGHamiz7DNJ0M6Ywer6PHOXqo8lqqvA74TRYXfQAA4Msh8gBQ
lMgDQFEiDwBFiTwAFCXyAFCUyANAUSIPAEWJPAAUJfIAUJTIA0BRIg8ARa0u+gDwv5nDApBKi0yW
i8vxaxmn0x5HuXBDW8YzLnx70i/0+Fw348Es/kbpx508ABQl8gBQlMgDQFEiDwBFiTwAFCXyAFCU
yANAUSIPAEWJPAAUJfIAUJTIA0BRIg8ARVlQw+xVWg6TWgx7c9mHcuF6/F2M0zr+u+hxjh4sl+F/
4k4eAIoSeQAoSuQBoCiRB4CiRB4AihJ5AChK5AGgKJEHgKJEHgCKEnkAKErkAaAokQeAoiw04Dfq
sQxlapseR7lwi8VePGMc1x1Okhva8qKP0FrL/zZ6vI65/H1WWaDE/LiTB4CiRB4AihJ5AChK5AGg
KJEHgKJEHgCKEnkAKErkAaAokQeAokQeAIoSeQAoyvOSZ2gYduJnxs9Fj2dy93iG/mp5JR0RG6fz
eMbWcj+esRhW8Ywer+X47F50/WLYjs/QOrwXrcN70cNmPPB7zn/jTh4AihJ5AChK5AGgKJEHgKJE
HgCKEnkAKErkAaAokQeAokQeAIoSeQAoSuQBoCiRB4CiOmxn4L9KF8wMbRmfYWqbfIblMv9p6LDI
ZNlhRo/lMj3sLq/FM043T6Prb+z+fnyGxyc/i2dsZrKgZrm4HH/Xxuk0ur7Hb0YPPZZ8zeW1pNzJ
A0BRIg8ARYk8ABQl8gBQlMgDQFEiDwBFiTwAFCXyAFCUyANAUSIPAEWJPAAUJfIAUFSJB/D/UpWl
BD2WugyLnfgcm83j+L3Y2Xolfi09/Pb2N6LrPzz5bnyG27tvxTO+2Hwaz3hlkS92+Xj8YTzjzuKN
6Pqfnv1DfIYeC3/ONofxjLHDkptxXMcz5mAuy7XmIu2aO3kAKErkAaAokQeAokQeAIoSeQAoSuQB
oCiRB4CiRB4AihJ5AChK5AGgKJEHgKLKPN93TtJnDQ9t2esokcViL57x/O5r8Yzz8SSesbu8Gl2/
367FZ3huyt/Px8PP4xn7U/5aTofjeMayZc+NfzLdi8+wGnbjGc/O78czjs4exjN6mKbsu7YZD+Km
9NhB0kOV59+7kweAokQeAIoSeQAoSuQBoCiRB4CiRB4AihJ5AChK5AGgKJEHgKJEHgCKEnkAKErk
AaCobEPEL/RYKDCXZQA9Xsti2A4PkX8sq8V+POPa9p14Ro/lHa+s/jCe0cJP9XqHpS6X2k484/Xl
jXjG9e38f/v7x5t4xqPxKLr+cPFFfIZb46vxjPNlvqxnffpZPGMVLmH6D/HCnvj3s9KSmzm00Z08
ABQl8gBQlMgDQFEiDwBFiTwAFCXyAFCUyANAUSIPAEWJPAAUJfIAUJTIA0BRIg8ARc1iKUwvi2Ev
XwbQ8sUb8YKaDna3Xoxn7K1eiGfcbL8Vz/idIX8tp+MYXf/Nm8v4DJ+s8/+pX+iwd+PKVvZetNba
/ir/nvzgcfY9OctfRnvv6CCe8dHivXjG5SFfPHTY8oU9683D6PpnHRbtjOM6njGXhWdz4E4eAIoS
eQAoSuQBoCiRB4CiRB4AihJ5AChK5AGgKJEHgKJEHgCKEnkAKErkAaCo1UUfYG7m8Nz57dX1eMZi
yD/aZ2f34xm3V1+LZxxN5/GMN6/uRNffPYqP0H7vylk+pIOPDrfiGW9cO41nvPPy0+j6b929Ep/h
tZ1L8Yz75/mM5ZR/X9dj9tz51lo7Pn8Sz5iD5fL5eMnDZvO4xPPv3ckDQFEiDwBFiTwAFCXyAFCU
yANAUSIPAEWJPAAUJfIAUJTIA0BRIg8ARYk8ABQl8gBQ1GoYduIH+U/TSfwg/x7nGKd1fI7lcLnD
ObLlHT2Wy2wv9uMZN1avxzMujc/FM9651eP9yJbDbC3iP4s25iPamzc+j2e8fWuMZ2zG/P7gk4Or
0fV/eutZfIZv38+Xyzx/ejOecTTkG5BWQ7aEqbXWVotsxtRhmVSPW89pPMmHFOFOHgCKEnkAKErk
AaAokQeAokQeAIoSeQAoSuQBoCiRB4CiRB4AihJ5AChK5AGgKJEHgKJWPZbL9NDjHIthL14BshkP
4nOsljeic5x3WK5wZeuleMad8ZV4xut7u/GMT9fxiPbnLz+Jrr9/tBef4S++/r14xvbecTxjsdzE
M7717h/l5xiyr+v7T/MlTH98I18M8+Tu9XjGZsq3F3377IN4RvrbM3ZYULPZPJ5Fk5aLi19W1oM7
eQAoSuQBoCiRB4CiRB4AihJ5AChK5AGgKJEHgKJEHgCKEnkAKErkAaAokQeAokQeAIpaXfQBfqnH
cpmp5Ys3eiwlSG3GfAnJg/N8WcVLi3zJzaPTMZ7xzZv553p97/BCr2+ttWGZvxfrp5fyGet82c6f
vf2P8Yzvfv/r0fXvvPpJfIafPLwZzzgb88/13nm+hWl/+UI8Y2zZgpmjs3xBTbrgq7XWNuNBfI4e
y8p6dG2c1tE53MkDQFEiDwBFiTwAFCXyAFCUyANAUSIPAEWJPAAUJfIAUJTIA0BRIg8ARYk8ABQ1
m2fX93ju/DSdxM8antoyftbwEJ5if/tWeoR2bXk7nrE95n8el1f5/5EfHeYznn6SvR9/+drP4jP8
5IPX4xlvvfXP8YyXbr0fz/j+3/5JPON3X/4suv7Bk6vxGR6cbMczrm4t4xn38ke+t622G8+4ucz+
Rj88zT7T1lrbbB7P4pnxPZaYpM+d78GdPAAUJfIAUJTIA0BRIg8ARYk8ABQl8gBQlMgDQFEiDwBF
iTwAFCXyAFCUyANAUSIPAEXNZkFNDz2WEszB8fmTfEiHBTVP2mE8Y2uRL804G+MRbX+VDTk+yxeZ
/MHX8sUwn//by/GMG5v8f/vjs614xubplej6f3nwYnyGw/P8vRg7/OpcGvK/r+fGV+IZ3zn5q+j6
oeXLelbLG/E7er55cOGLYVprbRh28kU54eI1d/IAUJTIA0BRIg8ARYk8ABQl8gBQlMgDQFEiDwBF
iTwAFCXyAFCUyANAUSIPAEWJPAAUNZsFNT0WG0xtU+Ic55t8Qc1iJh/tj9fP4hlf3b0Uz9hdZgtq
Hhx2OMMnX4ln3HjhUTzj7979Rjzj5n7+uY5TtkPk+s5JfIYvTvPvyY9Ovohn3GzZsp7WWvvO2V/H
M/a3b0XXH509jM+wmfLPtceysnFax0tu0uUyPbiTB4CiRB4AihJ5AChK5AGgKJEHgKJEHgCKEnkA
KErkAaAokQeAokQeAIoSeQAoajUMO/Ezfnvo8ZzgHq9lWOykI1qbzqPLl4v9+AjHLX+2+HrIn8n9
YrsTz1gO+XPj02eUn42X4zP08OBZ/ozzW5cO4hnr0+14xt/fy56T/vQsfyz4R4f5vos3dl+IZ/zT
yd14xqrDb1e682IMf/taa20c1/GMOTwzfi7cyQNAUSIPAEWJPAAUJfIAUJTIA0BRIg8ARYk8ABQl
8gBQlMgDQFEiDwBFiTwAFCXyAFDUyoP8f12P5QhDW0bXb8bD+AzrzcN4xvl4HM+4tnopnvHx0Uk8
4/ZetlDl7s

In [25]:
scatter(xs, ys, aspect_ratio=:equal, alpha=0.3)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -25 
 
 
 0 
 
 
 25 
 
 
 -25 
 
 
 0 
 
 
 25 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
<circle clip-path="url(#clip02)" style="fill:#0099ff; stroke:none; fill-opacity:0.3" cx="301.693" cy="176.835

In [27]:
f(x, y) = x*y

f (generic function with 1 method)

In [28]:
f(3, 4)

12

In [29]:
α = 3

3

Vamos a ver la **ecuación**

$$y = \exp(x^2)$$